### ISSUE TITLE
Why example raises an error? ("conda install ???" in order to be able to "import ovr")

### ISSUE THREAD

**Issue by georgydunaev** [cmbruns/pyovr#15]
I am trying to start example of code from main page.

Is Oculus Runtime 1.3 installed on this machine?
Traceback (most recent call last):
  File "D:\Georgy2\mypyscripts\ovr02.py", line 3, in <module>
    import ovr
  File "D:\Georgy2\anaconda_x32\lib\site-packages\ovr__init__.py", line 5, in <
module>
    from _ovr130 import *
  File "D:\Georgy2\anaconda_x32\lib\site-packages\ovr_ovr130.py", line 28, in <
module>
    libovr = CDLL(_libname)
  File "D:\Georgy2\anaconda_x32\lib\ctypes__init__.py", line 362, in **init**
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

**Comment by georgydunaev** [comment]
I am on Windows and only targeting windows. The version of OVRServiceLauncer is 6.0.1.64681. Where can I see a runtime version? I need 1.3. (I have display driver version 1.2.6. Is it related to runtime? ) I've installed the setup (www3.oculus.com/en-us/setup) yesterday. I suppose it has a runtime in it. I also can run demo. But where can I see the version of runtime? And what should I do to fix error?
