### ISSUE TITLE
Update for SDK 1.11

### ISSUE THREAD

**Issue by cmbruns** [cmbruns/pyovr#18]
https://forums.oculus.com/community/discussion/49275/rift-1-11-release-notes
https://github.com/cmbruns/pyovr/wiki/Release-Checklist
https://developer3.oculus.com/downloads/

**Comment by ckbruns** [comment]
Failed first test - will need help fixing

Traceback (most recent call last):
  File "E:\ckbruns\Documents\git\pyovr\examples\glut\rift_demo_glut.py", line 9, in <module>
    from ovr.rift_gl_renderer_compatibility import RiftGLRendererCompatibility
  File "E:\ckbruns\Documents\git\pyovr\ovr\__init__.py", line 5, in <module>
    from _ovr1110 import *
  File "E:\ckbruns\Documents\git\pyovr\ovr\_ovr1110.py", line 1158, in <module>
    ControllerType_Touch     = (ovrControllerType_LTouch | ControllerType_RTouch)
NameError: name 'ovrControllerType_LTouch' is not defined

**Comment by cmbruns-hhmi** [comment]
OK. It looks like we'll need to adjust the symbol renaming to get rid of that "ovr" in "ovrControllerType_LTouch".

**Comment by cmbruns-hhmi** [comment]
I'm glad it's fixed now. Nice work.
